/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// AuthenticatorAttachmentEnum : * `platform` - Platform * `cross-platform` - Cross Platform
/// * `platform` - Platform * `cross-platform` - Cross Platform
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticatorAttachmentEnum {
    #[serde(rename = "platform")]
    Platform,
    #[serde(rename = "cross-platform")]
    CrossPlatform,

}

impl ToString for AuthenticatorAttachmentEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Platform => String::from("platform"),
            Self::CrossPlatform => String::from("cross-platform"),
        }
    }
}

impl Default for AuthenticatorAttachmentEnum {
    fn default() -> AuthenticatorAttachmentEnum {
        Self::Platform
    }
}

