/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// AuthenticatedSessionUserAgent : Get parsed user agent
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticatedSessionUserAgent {
    #[serde(rename = "device")]
    pub device: Box<models::AuthenticatedSessionUserAgentDevice>,
    #[serde(rename = "os")]
    pub os: Box<models::AuthenticatedSessionUserAgentOs>,
    #[serde(rename = "user_agent")]
    pub user_agent: Box<models::AuthenticatedSessionUserAgentUserAgent>,
    #[serde(rename = "string")]
    pub string: String,
}

impl AuthenticatedSessionUserAgent {
    /// Get parsed user agent
    pub fn new(device: models::AuthenticatedSessionUserAgentDevice, os: models::AuthenticatedSessionUserAgentOs, user_agent: models::AuthenticatedSessionUserAgentUserAgent, string: String) -> AuthenticatedSessionUserAgent {
        AuthenticatedSessionUserAgent {
            device: Box::new(device),
            os: Box::new(os),
            user_agent: Box::new(user_agent),
            string,
        }
    }
}

