/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// AuthModeEnum : * `static` - Static * `prompt` - Prompt
/// * `static` - Static * `prompt` - Prompt
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthModeEnum {
    #[serde(rename = "static")]
    Static,
    #[serde(rename = "prompt")]
    Prompt,

}

impl ToString for AuthModeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Static => String::from("static"),
            Self::Prompt => String::from("prompt"),
        }
    }
}

impl Default for AuthModeEnum {
    fn default() -> AuthModeEnum {
        Self::Static
    }
}

