/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CapabilitiesEnum : * `can_save_media` - Can Save Media * `can_geo_ip` - Can Geo Ip * `can_asn` - Can Asn * `can_impersonate` - Can Impersonate * `can_debug` - Can Debug * `is_enterprise` - Is Enterprise
/// * `can_save_media` - Can Save Media * `can_geo_ip` - Can Geo Ip * `can_asn` - Can Asn * `can_impersonate` - Can Impersonate * `can_debug` - Can Debug * `is_enterprise` - Is Enterprise
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CapabilitiesEnum {
    #[serde(rename = "can_save_media")]
    CanSaveMedia,
    #[serde(rename = "can_geo_ip")]
    CanGeoIp,
    #[serde(rename = "can_asn")]
    CanAsn,
    #[serde(rename = "can_impersonate")]
    CanImpersonate,
    #[serde(rename = "can_debug")]
    CanDebug,
    #[serde(rename = "is_enterprise")]
    IsEnterprise,

}

impl ToString for CapabilitiesEnum {
    fn to_string(&self) -> String {
        match self {
            Self::CanSaveMedia => String::from("can_save_media"),
            Self::CanGeoIp => String::from("can_geo_ip"),
            Self::CanAsn => String::from("can_asn"),
            Self::CanImpersonate => String::from("can_impersonate"),
            Self::CanDebug => String::from("can_debug"),
            Self::IsEnterprise => String::from("is_enterprise"),
        }
    }
}

impl Default for CapabilitiesEnum {
    fn default() -> CapabilitiesEnum {
        Self::CanSaveMedia
    }
}

