/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ConnectionToken : ConnectionToken Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionToken {
    #[serde(rename = "pk")]
    pub pk: uuid::Uuid,
    #[serde(rename = "provider")]
    pub provider: i32,
    #[serde(rename = "provider_obj")]
    pub provider_obj: Box<models::RacProvider>,
    #[serde(rename = "endpoint")]
    pub endpoint: uuid::Uuid,
    #[serde(rename = "endpoint_obj")]
    pub endpoint_obj: Box<models::Endpoint>,
    #[serde(rename = "user")]
    pub user: Box<models::GroupMember>,
}

impl ConnectionToken {
    /// ConnectionToken Serializer
    pub fn new(pk: uuid::Uuid, provider: i32, provider_obj: models::RacProvider, endpoint: uuid::Uuid, endpoint_obj: models::Endpoint, user: models::GroupMember) -> ConnectionToken {
        ConnectionToken {
            pk,
            provider,
            provider_obj: Box::new(provider_obj),
            endpoint,
            endpoint_obj: Box::new(endpoint_obj),
            user: Box::new(user),
        }
    }
}

