/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ContextualFlowInfoLayoutEnum : * `stacked` - STACKED * `content_left` - CONTENT_LEFT * `content_right` - CONTENT_RIGHT * `sidebar_left` - SIDEBAR_LEFT * `sidebar_right` - SIDEBAR_RIGHT
/// * `stacked` - STACKED * `content_left` - CONTENT_LEFT * `content_right` - CONTENT_RIGHT * `sidebar_left` - SIDEBAR_LEFT * `sidebar_right` - SIDEBAR_RIGHT
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContextualFlowInfoLayoutEnum {
    #[serde(rename = "stacked")]
    Stacked,
    #[serde(rename = "content_left")]
    ContentLeft,
    #[serde(rename = "content_right")]
    ContentRight,
    #[serde(rename = "sidebar_left")]
    SidebarLeft,
    #[serde(rename = "sidebar_right")]
    SidebarRight,

}

impl ToString for ContextualFlowInfoLayoutEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Stacked => String::from("stacked"),
            Self::ContentLeft => String::from("content_left"),
            Self::ContentRight => String::from("content_right"),
            Self::SidebarLeft => String::from("sidebar_left"),
            Self::SidebarRight => String::from("sidebar_right"),
        }
    }
}

impl Default for ContextualFlowInfoLayoutEnum {
    fn default() -> ContextualFlowInfoLayoutEnum {
        Self::Stacked
    }
}

