/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// Coordinate : Coordinates for diagrams
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Coordinate {
    #[serde(rename = "x_cord")]
    pub x_cord: i32,
    #[serde(rename = "y_cord")]
    pub y_cord: i32,
}

impl Coordinate {
    /// Coordinates for diagrams
    pub fn new(x_cord: i32, y_cord: i32) -> Coordinate {
        Coordinate {
            x_cord,
            y_cord,
        }
    }
}

