/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// DeniedActionEnum : * `message_continue` - Message Continue * `message` - Message * `continue` - Continue
/// * `message_continue` - Message Continue * `message` - Message * `continue` - Continue
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeniedActionEnum {
    #[serde(rename = "message_continue")]
    MessageContinue,
    #[serde(rename = "message")]
    Message,
    #[serde(rename = "continue")]
    Continue,

}

impl ToString for DeniedActionEnum {
    fn to_string(&self) -> String {
        match self {
            Self::MessageContinue => String::from("message_continue"),
            Self::Message => String::from("message"),
            Self::Continue => String::from("continue"),
        }
    }
}

impl Default for DeniedActionEnum {
    fn default() -> DeniedActionEnum {
        Self::MessageContinue
    }
}

