/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// DigitsEnum : * `6` - 6 digits, widely compatible * `8` - 8 digits, not compatible with apps like Google Authenticator
/// * `6` - 6 digits, widely compatible * `8` - 8 digits, not compatible with apps like Google Authenticator
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DigitsEnum {
    #[serde(rename = "6")]
    Variant6,
    #[serde(rename = "8")]
    Variant8,

}

impl ToString for DigitsEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Variant6 => String::from("6"),
            Self::Variant8 => String::from("8"),
        }
    }
}

impl Default for DigitsEnum {
    fn default() -> DigitsEnum {
        Self::Variant6
    }
}

