/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// DuoResponseEnum : * `success` - Success * `waiting` - Waiting * `invalid` - Invalid
/// * `success` - Success * `waiting` - Waiting * `invalid` - Invalid
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DuoResponseEnum {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "waiting")]
    Waiting,
    #[serde(rename = "invalid")]
    Invalid,

}

impl ToString for DuoResponseEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Success => String::from("success"),
            Self::Waiting => String::from("waiting"),
            Self::Invalid => String::from("invalid"),
        }
    }
}

impl Default for DuoResponseEnum {
    fn default() -> DuoResponseEnum {
        Self::Success
    }
}

