/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// GeoipBindingEnum : * `no_binding` - No Binding * `bind_continent` - Bind Continent * `bind_continent_country` - Bind Continent Country * `bind_continent_country_city` - Bind Continent Country City
/// * `no_binding` - No Binding * `bind_continent` - Bind Continent * `bind_continent_country` - Bind Continent Country * `bind_continent_country_city` - Bind Continent Country City
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GeoipBindingEnum {
    #[serde(rename = "no_binding")]
    NoBinding,
    #[serde(rename = "bind_continent")]
    BindContinent,
    #[serde(rename = "bind_continent_country")]
    BindContinentCountry,
    #[serde(rename = "bind_continent_country_city")]
    BindContinentCountryCity,

}

impl ToString for GeoipBindingEnum {
    fn to_string(&self) -> String {
        match self {
            Self::NoBinding => String::from("no_binding"),
            Self::BindContinent => String::from("bind_continent"),
            Self::BindContinentCountry => String::from("bind_continent_country"),
            Self::BindContinentCountryCity => String::from("bind_continent_country_city"),
        }
    }
}

impl Default for GeoipBindingEnum {
    fn default() -> GeoipBindingEnum {
        Self::NoBinding
    }
}

