/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// Group : Group Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Group {
    #[serde(rename = "pk")]
    pub pk: uuid::Uuid,
    #[serde(rename = "num_pk")]
    pub num_pk: i32,
    #[serde(rename = "name")]
    pub name: String,
    /// Users added to this group will be superusers.
    #[serde(rename = "is_superuser", skip_serializing_if = "Option::is_none")]
    pub is_superuser: Option<bool>,
    #[serde(rename = "parent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Option<uuid::Uuid>>,
    #[serde(rename = "parent_name", deserialize_with = "Option::deserialize")]
    pub parent_name: Option<String>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<i32>>,
    #[serde(rename = "users_obj")]
    pub users_obj: Vec<models::GroupMember>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "roles_obj")]
    pub roles_obj: Vec<models::Role>,
}

impl Group {
    /// Group Serializer
    pub fn new(pk: uuid::Uuid, num_pk: i32, name: String, parent_name: Option<String>, users_obj: Vec<models::GroupMember>, roles_obj: Vec<models::Role>) -> Group {
        Group {
            pk,
            num_pk,
            name,
            is_superuser: None,
            parent: None,
            parent_name,
            users: None,
            users_obj,
            attributes: None,
            roles: None,
            roles_obj,
        }
    }
}

