/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// LdapSyncStatus : LDAP Source sync status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LdapSyncStatus {
    #[serde(rename = "is_running")]
    pub is_running: bool,
    #[serde(rename = "tasks")]
    pub tasks: Vec<models::SystemTask>,
}

impl LdapSyncStatus {
    /// LDAP Source sync status
    pub fn new(is_running: bool, tasks: Vec<models::SystemTask>) -> LdapSyncStatus {
        LdapSyncStatus {
            is_running,
            tasks,
        }
    }
}

