/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "provider_model")]
pub enum ModelRequest {
    #[serde(rename="authentik_providers_ldap.ldapprovider")]
    AuthentikProvidersLdapPeriodLdapprovider(Box<models::LdapProviderRequest>),
    #[serde(rename="authentik_providers_oauth2.oauth2provider")]
    AuthentikProvidersOauth2PeriodOauth2provider(Box<models::OAuth2ProviderRequest>),
    #[serde(rename="authentik_providers_proxy.proxyprovider")]
    AuthentikProvidersProxyPeriodProxyprovider(Box<models::ProxyProviderRequest>),
    #[serde(rename="authentik_providers_rac.racprovider")]
    AuthentikProvidersRacPeriodRacprovider(Box<models::RacProviderRequest>),
    #[serde(rename="authentik_providers_radius.radiusprovider")]
    AuthentikProvidersRadiusPeriodRadiusprovider(Box<models::RadiusProviderRequest>),
    #[serde(rename="authentik_providers_saml.samlprovider")]
    AuthentikProvidersSamlPeriodSamlprovider(Box<models::SamlProviderRequest>),
    #[serde(rename="authentik_providers_scim.scimprovider")]
    AuthentikProvidersScimPeriodScimprovider(Box<models::ScimProviderRequest>),
}

impl Default for ModelRequest {
    fn default() -> Self {
        Self::AuthentikProvidersLdapPeriodLdapprovider(Default::default())
    }
}


