/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// NetworkBindingEnum : * `no_binding` - No Binding * `bind_asn` - Bind Asn * `bind_asn_network` - Bind Asn Network * `bind_asn_network_ip` - Bind Asn Network Ip
/// * `no_binding` - No Binding * `bind_asn` - Bind Asn * `bind_asn_network` - Bind Asn Network * `bind_asn_network_ip` - Bind Asn Network Ip
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NetworkBindingEnum {
    #[serde(rename = "no_binding")]
    NoBinding,
    #[serde(rename = "bind_asn")]
    BindAsn,
    #[serde(rename = "bind_asn_network")]
    BindAsnNetwork,
    #[serde(rename = "bind_asn_network_ip")]
    BindAsnNetworkIp,

}

impl ToString for NetworkBindingEnum {
    fn to_string(&self) -> String {
        match self {
            Self::NoBinding => String::from("no_binding"),
            Self::BindAsn => String::from("bind_asn"),
            Self::BindAsnNetwork => String::from("bind_asn_network"),
            Self::BindAsnNetworkIp => String::from("bind_asn_network_ip"),
        }
    }
}

impl Default for NetworkBindingEnum {
    fn default() -> NetworkBindingEnum {
        Self::NoBinding
    }
}

