/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// PasswordChallenge : Password challenge UI fields
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordChallenge {
    #[serde(rename = "type")]
    pub r#type: models::ChallengeChoices,
    #[serde(rename = "flow_info", skip_serializing_if = "Option::is_none")]
    pub flow_info: Option<Box<models::ContextualFlowInfo>>,
    #[serde(rename = "component", skip_serializing_if = "Option::is_none")]
    pub component: Option<String>,
    #[serde(rename = "response_errors", skip_serializing_if = "Option::is_none")]
    pub response_errors: Option<std::collections::HashMap<String, Vec<models::ErrorDetail>>>,
    #[serde(rename = "pending_user")]
    pub pending_user: String,
    #[serde(rename = "pending_user_avatar")]
    pub pending_user_avatar: String,
    #[serde(rename = "recovery_url", skip_serializing_if = "Option::is_none")]
    pub recovery_url: Option<String>,
}

impl PasswordChallenge {
    /// Password challenge UI fields
    pub fn new(r#type: models::ChallengeChoices, pending_user: String, pending_user_avatar: String) -> PasswordChallenge {
        PasswordChallenge {
            r#type,
            flow_info: None,
            component: None,
            response_errors: None,
            pending_user,
            pending_user_avatar,
            recovery_url: None,
        }
    }
}

