/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// PatchedDenyStageRequest : DenyStage Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedDenyStageRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "flow_set", skip_serializing_if = "Option::is_none")]
    pub flow_set: Option<Vec<models::FlowSetRequest>>,
    #[serde(rename = "deny_message", skip_serializing_if = "Option::is_none")]
    pub deny_message: Option<String>,
}

impl PatchedDenyStageRequest {
    /// DenyStage Serializer
    pub fn new() -> PatchedDenyStageRequest {
        PatchedDenyStageRequest {
            name: None,
            flow_set: None,
            deny_message: None,
        }
    }
}

