/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// PatchedPlexSourceConnectionRequest : Plex Source connection Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedPlexSourceConnectionRequest {
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
    #[serde(rename = "plex_token", skip_serializing_if = "Option::is_none")]
    pub plex_token: Option<String>,
}

impl PatchedPlexSourceConnectionRequest {
    /// Plex Source connection Serializer
    pub fn new() -> PatchedPlexSourceConnectionRequest {
        PatchedPlexSourceConnectionRequest {
            identifier: None,
            plex_token: None,
        }
    }
}

