/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ProtocolEnum : * `rdp` - Rdp * `vnc` - Vnc * `ssh` - Ssh
/// * `rdp` - Rdp * `vnc` - Vnc * `ssh` - Ssh
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProtocolEnum {
    #[serde(rename = "rdp")]
    Rdp,
    #[serde(rename = "vnc")]
    Vnc,
    #[serde(rename = "ssh")]
    Ssh,

}

impl ToString for ProtocolEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Rdp => String::from("rdp"),
            Self::Vnc => String::from("vnc"),
            Self::Ssh => String::from("ssh"),
        }
    }
}

impl Default for ProtocolEnum {
    fn default() -> ProtocolEnum {
        Self::Rdp
    }
}

