/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ResidentKeyRequirementEnum : * `discouraged` - Discouraged * `preferred` - Preferred * `required` - Required
/// * `discouraged` - Discouraged * `preferred` - Preferred * `required` - Required
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResidentKeyRequirementEnum {
    #[serde(rename = "discouraged")]
    Discouraged,
    #[serde(rename = "preferred")]
    Preferred,
    #[serde(rename = "required")]
    Required,

}

impl ToString for ResidentKeyRequirementEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Discouraged => String::from("discouraged"),
            Self::Preferred => String::from("preferred"),
            Self::Required => String::from("required"),
        }
    }
}

impl Default for ResidentKeyRequirementEnum {
    fn default() -> ResidentKeyRequirementEnum {
        Self::Discouraged
    }
}

