/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// SeverityEnum : * `notice` - Notice * `warning` - Warning * `alert` - Alert
/// * `notice` - Notice * `warning` - Warning * `alert` - Alert
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SeverityEnum {
    #[serde(rename = "notice")]
    Notice,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "alert")]
    Alert,

}

impl ToString for SeverityEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Notice => String::from("notice"),
            Self::Warning => String::from("warning"),
            Self::Alert => String::from("alert"),
        }
    }
}

impl Default for SeverityEnum {
    fn default() -> SeverityEnum {
        Self::Notice
    }
}

