/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// SystemInfoRuntime : Get versions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemInfoRuntime {
    #[serde(rename = "python_version")]
    pub python_version: String,
    #[serde(rename = "gunicorn_version")]
    pub gunicorn_version: String,
    #[serde(rename = "environment")]
    pub environment: String,
    #[serde(rename = "architecture")]
    pub architecture: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "uname")]
    pub uname: String,
}

impl SystemInfoRuntime {
    /// Get versions
    pub fn new(python_version: String, gunicorn_version: String, environment: String, architecture: String, platform: String, uname: String) -> SystemInfoRuntime {
        SystemInfoRuntime {
            python_version,
            gunicorn_version,
            environment,
            architecture,
            platform,
            uname,
        }
    }
}

