/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// TotpDevice : Serializer for totp authenticator devices
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotpDevice {
    /// The human-readable name of this device.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "pk")]
    pub pk: i32,
}

impl TotpDevice {
    /// Serializer for totp authenticator devices
    pub fn new(name: String, pk: i32) -> TotpDevice {
        TotpDevice {
            name,
            pk,
        }
    }
}

