/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// UserFieldsEnum : * `email` - E Mail * `username` - Username * `upn` - Upn
/// * `email` - E Mail * `username` - Username * `upn` - Upn
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserFieldsEnum {
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "username")]
    Username,
    #[serde(rename = "upn")]
    Upn,

}

impl ToString for UserFieldsEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Email => String::from("email"),
            Self::Username => String::from("username"),
            Self::Upn => String::from("upn"),
        }
    }
}

impl Default for UserFieldsEnum {
    fn default() -> UserFieldsEnum {
        Self::Email
    }
}

