/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPasswordSetRequest {
    #[serde(rename = "password")]
    pub password: String,
}

impl UserPasswordSetRequest {
    pub fn new(password: String) -> UserPasswordSetRequest {
        UserPasswordSetRequest {
            password,
        }
    }
}

