/*
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: hello@goauthentik.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// UserLogoutStageRequest : UserLogoutStage Serializer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserLogoutStageRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "flow_set", skip_serializing_if = "Option::is_none")]
    pub flow_set: Option<Vec<models::FlowSetRequest>>,
}

impl UserLogoutStageRequest {
    /// UserLogoutStage Serializer
    pub fn new(name: String) -> UserLogoutStageRequest {
        UserLogoutStageRequest {
            name,
            flow_set: None,
        }
    }
}

